# Generated by Django 3.1.4 on 2020-12-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edostemplate',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
